# ~/.config/starship.toml

# Modified from the Tokyo Night preset: https://starship.rs/presets/tokyo-night

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# A continuation prompt that displays two filled-in arrows
continuation_prompt = '▶▶ '

format = """
[ ](bg:#769ff0 fg:#e3e5e5)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
$kubernetes\
${env_var.VIRTUAL_ENV_PROMPT}\
[](fg:#212736 bg:#1d2230)\
$fill\
$time\
[ ](fg:#1d2230)\
\n$character"""

[fill]
symbol = " "
style = 'fg:#a0a9cb'

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'
conflicted = '=${count}'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
untracked = '?${count}'
stashed = '$${count}'
modified = '!${count}'
staged = '+${count}'
renamed = '»${count}'
deleted = '✘${count}'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

# this isn't working so well right now.
[kubernetes]
disabled = true
symbol = "☸"
style = "bg:#212736"
format = '[ ($symbol $context) ]($style)'

# this is used to display the poetry virtual environment.
# it's a rough hack, and unfortunately the prompt doesn't go
# away until VIRTUAL_ENV_PROMP is unset
[env_var.VIRTUAL_ENV_PROMPT]
variable = 'VIRTUAL_ENV_PROMPT'
disabled = false
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($env_value) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
