# ~/.config/starship.toml

# Modified from the Tokyo Night preset: https://starship.rs/presets/tokyo-night

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# A continuation prompt that displays two filled-in arrows
continuation_prompt = '▶▶ '

format = """
[ ](bg:#769ff0 fg:#e3e5e5)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
[](fg:#212736)\
$fill\
$kubernetes\
$cmd_duration\
$time\
[ ](fg:#1e1d2c)\
\n$character"""

right_format = """$python"""

[fill]
symbol = " "
style = 'fg:#a0a9cb'

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'
conflicted = '=${count}'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
untracked = '?${count}'
stashed = '$${count}'
modified = '!${count}'
staged = '+${count}'
renamed = '»${count}'
deleted = '✘${count}'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[kubernetes]
disabled = false
symbol = "☸"
style = "bg:#1e1d2c"
format = '[($symbol $context )]($style)'

[[kubernetes.contexts]]
# Warn me if I am in a production environment
context_pattern = "gke_.*_(?P<cluster>[\\w-]*prd[\\w-]+)"
style = "fg:red bg:#1d2230"
context_alias = "!! $cluster !!"

[[kubernetes.contexts]]
# Using capture groups
# Contexts from GKE, AWS and other cloud providers usually carry additional information, like the region/zone.
# The following entry matches on the GKE format (`gke_projectname_zone_cluster-name`)
# and renames every matching kube context into a more readable format (`gke-cluster-name`):
context_pattern = "gke_.*_(?P<cluster>[\\w-]+)"
context_alias = "$cluster"

[python]
disabled = false
symbol = ""
style = "fg:#769ff0 bg:#212736"
python_binary = ['python3', 'python']
detect_files = ['poetry.lock', '.python-version', 'Pipfile', '__init__.py', 'pyproject.toml', 'requirements.txt', 'setup.py', 'tox.ini']
format = '[( $symbol $virtualenv)]($style)'

[cmd_duration]
min_time = 500
style = "bg:#1e1d2c fg:bold yellow"
format = '[󰦖 $duration]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1e1d2c"
format = '[[  $time ](fg:#a0a9cb)]($style)'
